### ISSUE TITLE
BuildPart is sometimes a Solid instead of a Compound

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#112]
```py
from build123d import *

with BuildPart() as c:
    Sphere(1)
```
```py
type(c.part)
build123d.direct_api.Solid
```
```py
with BuildPart() as bp:
    Box(1,1,1)
    with Locations((0,3,0)):
        Box(0.5,.5,2)
```
```py
type(bp.part)
build123d.direct_api.Compound
```

**Comment by gumyr** [comment]
Thanks for generating the issue - actually related to adding children to a BuildPart part.  

Although it was my original intention for all of the Builders to generate Compounds, this illustrates that OCCT is really capable enough to deal with all Shapes, Solids or Compounds as appropriate.  So I'm wondering now if the real problem here is that there is no way in BuildPart to add children. So...

If there were an `AddChildren` and `AssignParent` classes in BuildPart that would ensure the "part" was a Compound and then add children with `part.children = children` or `part.parent = parent` (taking into consideration that "children" and "parent" could be builders), would that be sufficient?  There would be no need for the user to assign children with the direct api - although the direct api would be available if needed.

**Comment by gumyr** [comment]
As part of the algebra work, BuildPart always works with a subclass of Compound called Part.
```py
from build123d import *

with BuildPart() as c:
    Sphere(1)

print(type(c.part))

with BuildPart() as bp:
    Box(1, 1, 1)
    with Locations((0, 3, 0)):
        Box(0.5, 0.5, 2)

print(type(c.part))
```
```
<class 'build123d.topology.Part'>
<class 'build123d.topology.Part'>
```

Likewise, BuildSketch works with class Sketch and BuildLine works with Curve.
