### ISSUE TITLE
sweep over CenterArc does not behave as expected

### ISSUE THREAD

**Issue by OvisMaximus** [gumyr/build123d#215]
Given the following code
```py
from build123d import *

ring_diameter = 110

with BuildPart(Plane.XZ) as part_builder:
    with BuildLine(Plane.XY) as sweep_path:
        a_clamp_width = 12
        CenterArc((-ring_diameter/2, 0), ring_diameter / 2, -a_clamp_width / 2, a_clamp_width)
        #Line((0, -5), (0, 5))

    with BuildSketch(Plane.XZ) as sketch_builder:
        Rectangle(4.0, 8.0, align=(Align.CENTER,Align.MIN))

    sweep()

show_object(part_builder.part.wrapped, name="part")
show_object(sweep_path.line.wrapped, name="sweep_path")
show_object(sketch_builder.sketch.wrapped, name="sketch")
```
As a reference for my expectation, uncomment the Line statement and disable the CenterArc line. this is the rendered part:
![image](https://user-images.githubusercontent.com/5701377/231987837-1f448159-de54-4884-b048-c5b082eb3a99.png)

and that's the sketch it is based upon, also matching my expectation:
![image](https://user-images.githubusercontent.com/5701377/231965932-acdcdc3a-2ced-4f04-81ba-21dc4fcf7c2d.png)

The unmodified code above should create a similar solid with two deltas, first the angle of the arc is not identical to the extruded width with < 5% delta and secondly the solids Y edges should not be straight but slightly bend. Instead we get:
![image](https://user-images.githubusercontent.com/5701377/231985611-56352d43-ee11-49fe-928d-a65f3e12855f.png)

**Comment by gumyr** [comment]
This issue is caused by a confusing feature, the ability to relocated the results of the operations.  As you have `Plane.XZ` as the workplane for BuildPart there was a relocation happening which clearly is unexpected.  This feature was too difficult to understand and has been removed.  The result is now:
![image](https://user-images.githubusercontent.com/85638518/232328886-4cb7d2f9-10bd-4aa5-8a14-f02df79a6409.png)
