### ISSUE TITLE
bad IDE integration

### ISSUE THREAD

**Issue by lypwig** [gumyr/build123d#26]
Some classes are incorrectly recognized as modules:

![image](https://user-images.githubusercontent.com/1665542/194806651-9c273e2f-31f6-4545-909b-7c8bb55f6746.png)

Same for enumerations:
![image](https://user-images.githubusercontent.com/1665542/194806766-921d98c0-11b3-4fd1-aa27-61991566bba2.png)

![image](https://user-images.githubusercontent.com/1665542/194808739-fedeb488-6c55-45f3-8929-9330688b0704.png)

I must type `bd.Mode.Mode` to have a correct auto-completion:
![image](https://user-images.githubusercontent.com/1665542/194806883-1af742b0-b42b-4d5f-b2ee-7aca37c7b049.png)

**Comment by gumyr** [comment]
I know this generally isn't the best python practice but when imported as `from build123d import *` all of these problems go away (at least in my environment).  It will take some research to figure out why alternative imports cause this issue.

**Comment by gumyr** [comment]
With commit 2b830ea472b267d41e3b6878d181ec679e2e6483, this problem seems to be solved. The issue was caused by importing from the top level of the project instead of from the appropriate module.

![image](https://user-images.githubusercontent.com/85638518/218333836-1255c933-3639-46a1-8492-30ed4841c4de.png)

![image](https://user-images.githubusercontent.com/85638518/218333849-15126d80-cbb0-4e5e-9505-892342d6f5c9.png)

![image](https://user-images.githubusercontent.com/85638518/218333885-182ab01b-6efd-4f3c-a2ab-fa71c81372ed.png)
