### ISSUE TITLE
bad behavior with GridLocation

### ISSUE THREAD

**Issue by lypwig** [gumyr/build123d#29]
This code:

```py
import build123d as b


def slot():
    with b.BuildSketch(mode=b.Mode.PRIVATE) as builder:
        with b.GridLocations(8, 0, 2, 1):
            b.Circle(1)

    return builder.sketch

with b.BuildSketch() as builder:
    b.Rectangle(60, 60)

    with b.GridLocations(20, 20, 2, 2):
        b.Rectangle(2, 2, mode=b.Mode.SUBTRACT)
        b.Add(slot(), mode=b.Mode.SUBTRACT)


if 'show_object' in locals():
    show_object(builder.sketch)
```

builds this:

![image](https://user-images.githubusercontent.com/1665542/195258312-2b7743a5-90d2-405e-ad1f-9eb40ac542fc.png)

And I'm expecting the same result with this code (I moved `b.Rectangle()`):

```py
def slot():
    with b.BuildSketch(mode=b.Mode.PRIVATE) as builder:
        b.Rectangle(2, 2)
        with b.GridLocations(8, 0, 2, 1):
            b.Circle(1)

    return builder.sketch

with b.BuildSketch() as builder:
    b.Rectangle(60, 60)

    with b.GridLocations(20, 20, 2, 2):
        b.Add(slot(), mode=b.Mode.SUBTRACT)
```

But instead I get this:

![image](https://user-images.githubusercontent.com/1665542/195258701-c65f68bb-d480-4fe1-8847-85e13c5ed47c.png)

This is a recent bug, I was not getting this strange behavior with an older version of build123d. Maybe related to #28 because both bugs appeared in my last build123d update.

**Comment by gumyr** [comment]
This turned out to be very tricky problem to solve.  The issue has to do with how many locations are active during the call to `slot()` and how many are active during the `add()`. If n locations are active during the call to `slot()` and the same n locations are active during the `Add` there will be n times n objects added - depending on the locations they can overlap and appear to be 9 objects as seen here.

Here are your two examples to illustrate (also note that nested locations is now possible so there is less need for this style of coding):

```py
def slot():
    with b.BuildSketch(mode=b.Mode.PRIVATE) as builder:
        with b.GridLocations(8, 0, 2, 1):
            b.Circle(1)
    return builder.sketch

with b.BuildSketch() as builder:
    b.Rectangle(60, 60)

    with b.GridLocations(20, 20, 2, 2):
        b.Rectangle(2, 2, mode=b.Mode.SUBTRACT)
        s = slot()
    b.Add(s, mode=b.Mode.SUBTRACT)
```
In this example the call to `slot()` is within the 2x2 GridLocations (so 12 objects are created) but the Add is outside to the Locatoins so 12 objects are added as shown here:
![image](https://user-images.githubusercontent.com/85638518/212961738-e9b19076-7e7b-4ec9-a239-c70afdffaaf4.png)

Alternatively:
```py
def slot():
    with b.BuildSketch(mode=b.Mode.PRIVATE) as builder:
        b.Rectangle(2, 2)
        with b.GridLocations(8, 0, 2, 1):
            b.Circle(1)
    return builder.sketch

with b.BuildSketch() as builder:
    b.Rectangle(60, 60)

    s = slot()
    with b.GridLocations(20, 20, 2, 2):
        b.Add(s, mode=b.Mode.SUBTRACT)
```
Here the `slot()` call is outside of the GridLocations so 3 objects are created and the Add is within the GridLocations so 3x4=12 objects are subtracted generating the same result as above.

One thing that can help will debugging these type of problems is to generate logs.  Here is an example:
```py
import logging
import build123d as b

logging.basicConfig(
    filename="issue-29.log",
    level=logging.DEBUG,
    format="%(name)s-%(levelname)5s %(asctime)s - [%(filename)s:%(lineno)s - %(funcName)20s() ] - %(message)s",
)
logging.info("Starting")
```
Which generates the following key logs:
```
build123d- INFO 2023-01-17 12:00:11,564 - [build_common.py:339 -            __enter__() ] - GridLocations is pushing 4 points: [(p=(-10.00, -10.00, 0.00), o=(-0.00, 0.00, -0.00)), (p=(-10.00, 10.00, 0.00), o=(-0.00, 0.00, -0.00)), (p=(10.00, -10.00, 0.00), o=(-0.00, 0.00, -0.00)), (p=(10.00, 10.00, 0.00), o=(-0.00, 0.00, -0.00))]
build123d-DEBUG 2023-01-17 12:00:11,568 - [build_sketch.py:164 -      _add_to_context() ] - Attempting to integrate 12 Face(s) into sketch with Mode=Mode.SUBTRACT
build123d-DEBUG 2023-01-17 12:00:11,581 - [direct_api.py:4464 - _post_detach_children() ] - Removing no children from 
build123d-DEBUG 2023-01-17 12:00:11,581 - [direct_api.py:4478 - _post_attach_children() ] - Adding no children to 
build123d-DEBUG 2023-01-17 12:00:11,583 - [build_sketch.py:185 -      _add_to_context() ] - Completed integrating 12 Face(s) into sketch with Mode=Mode.SUBTRACT
```
Note that 12 Faces are being integrated into the sketch as expected.
