### ISSUE TITLE
Specifying reference edge for chamfer broken

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#471]
```py
r = Rectangle(10,10)
e = (r.edges()<<Y)[0]
v = (e.vertices()<<X)[0]
```
<img width="185" alt="Screenshot" src="https://github.com/gumyr/build123d/assets/149267773/1ac96139-b9c5-43d4-975c-a46f7db269e6">

```py
print(f"{e in r.edges() = }")
print(f"{v in r.vertices() = }")
print(f"{v in e.vertices() = }")
chamfer(v, 5, angle=20, reference=e)
```
```
e in r.edges() = True
v in r.vertices() = True
v in e.vertices() = True
IndexError: list index out of range
```

**Comment by gumyr** [comment]
This problem is caused by how you've selected for `v`.  Consider this:
```py
r = Rectangle(10, 10)
e = (r.edges() << Axis.Y)[0]
v = (e.vertices() << Axis.X)[0]
print(f"{e.topo_parent=}")
print(f"{v.topo_parent=}")
```
```
e.topo_parent=Rectangle at 0x7f2839677490, label(), #children(0)
v.topo_parent=<build123d.topology.Edge object at 0x7f2839677700>
```
`v` is known to come from `e` but not `r` as that isn't the direct parent of `v`. Therefore, when the `chamfer` operation is attempted it fails because the parent object is `e` a single edge which can't be chamfered.

However, if the selection is done with:
```py
v = r.vertices().group_by(Axis.Y)[0].sort_by(Axis.X)[0]
print(f"{v.topo_parent=}")
```
```
v.topo_parent=Rectangle at 0x7f0637ab7490, label(), #children(0)
```
`v`'s parent is identified as `r` which can be chamfered so the operation succeeds.

The `reference` parameter does not refer to the topological parent of the vertex but selects which of the two edges are the "reference" when creating an asymmetric chamfer.  Here are both chamfer options:
![image](https://github.com/gumyr/build123d/assets/85638518/76556d06-3846-4fab-b4be-0da30d7e0f74)
