### ISSUE TITLE
Provide max fillet size in error message

### ISSUE THREAD

**Issue by proegssilb** [gumyr/build123d#591]
I'm converting some chamfers into fillets, and keep getting this error message:

```
ValueError: Failed creating a fillet with radius of 0.4, try a smaller value or use max_fillet() to find the largest valid fillet radius
```

OK, fair, I'm doing it wrong. But rather than me having to guess what the max fillet radius might be without even knowing that I have the right edges selected, could you just call `max_fillet()`  automatically and tell me what the max fillet is? The maximum fillet size could be very useful information in trying to find issues with my model, or making sure I have the right edges selected.

**Comment by gumyr** [comment]
`max_fillet` is a very error prone method, it works by trying values and catching exceptions.  Putting this into an exception handler seems very dangerous which is why the error message tells the user to try `max_fillet`.

When working with fillets and chamfers always display the edge(s) that you've selected prior to trying the fillet, e.g:
```py
with BuildPart() as p:
    ...
    the_selected_edges = p.edges()...
    #fillet(the_selected_edges, radius)

show(p, the_selected_edges)
```
